schema.name: dbo

spring:
  datasource:
    hikari:
      data-source-properties: sendStringParametersAsUnicode=false
    url: jdbc:sqlserver://localhost:1433;user=sa;password=Password1234!;trustServerCertificate=true;
  flyway:
    baselineOnMigrate: true
    locations: classpath:db/migration
    enabled: true
    placeholders:
      go: go
      datetimeoffset: datetimeoffset
      nonclustered: nonclustered
    schemas: ${schema.name}
    defaultSchema: ${schema.name}
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: false